export const DATA_FETCHING = "DATA_FETCHING";
export const DATA_FETCHED = "DATA_FETCHED";
export const DATA_ERROR = "DATA_ERROR";

export const ADD_TOWN_TO_LIST = "ADD_TOWN_TO_LIST";
export const SET_MAIN_TOWN = "SET_MAIN_TOWN";

export const CHANGE_SETTINGS_INPUT_CONTENT = "CHANGE_SETTINGS_INPUT_CONTENT";
