export const DATA_FETCHING = "DATA_FETCHING";
export const DATA_FETCHED = "DATA_FETCHED";
export const DATA_ERROR = "DATA_ERROR";

export const ADD_TOWN_TO_LIST = "ADD_TOWN_TO_LIST";
export const DELETE_TOWN_FROM_LIST = "DELETE_TOWN_FROM_LIST";
export const DEFAULT_TOWN_STATE = "DEFAULT_TOWN_STATE";
export const SET_MAIN_TOWN = "SET_MAIN_TOWN";

export const CHANGE_SETTINGS_INPUT_CONTENT = "CHANGE_SETTINGS_INPUT_CONTENT";
export const SETTINGS_INPUT_EMPTY = "SETTINGS_INPUT_EMPTY";

export const SHOW_SETTINGS = "SHOW_SETTINGS";
export const HIDE_SETTINGS = "HIDE_SETTINGS";
